name: flutter_docusign_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  syncfusion_flutter_pdf: ^20.4.54
  pdfx: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/sample_form.pdf